#!/bin/bash

# show ${RUNTIME_SCRIPT_DIR}
echo ${RUNTIME_SCRIPT_DIR}
# enter train workspace
cd ${RUNTIME_SCRIPT_DIR}

# 多模态缓存配置（唯一配置入口，可被外部覆盖）
export MM_CACHE_ENABLED=${MM_CACHE_ENABLED:-1}
export MM_CACHE_MAX_ENTRIES=${MM_CACHE_MAX_ENTRIES:-12}
echo "[cfg] MM_CACHE_ENABLED=${MM_CACHE_ENABLED}"
echo "[cfg] MM_CACHE_MAX_ENTRIES=${MM_CACHE_MAX_ENTRIES}"

# 用户数据缓存配置（唯一配置入口，可被外部覆盖）
export USER_CACHE_ENABLED=${USER_CACHE_ENABLED:-1}
export USER_CACHE_MAX_ENTRIES=${USER_CACHE_MAX_ENTRIES:-5000}
export USER_CACHE_READAHEAD=${USER_CACHE_READAHEAD:-0}
echo "[cfg] USER_CACHE_ENABLED=${USER_CACHE_ENABLED}"
echo "[cfg] USER_CACHE_MAX_ENTRIES=${USER_CACHE_MAX_ENTRIES}"
echo "[cfg] USER_CACHE_READAHEAD=${USER_CACHE_READAHEAD}"

# write your code below
python -u main.py

